name: Bug Report
description: Report a bug you've encountered
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Brief description of the bug
      placeholder: 'Brief one-line summary of the bug'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the bug
      placeholder: 'What did you expect to happen?'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step by step instructions to reproduce the bug
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: 'What did you expect to happen?'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: 'What did you see instead?'
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or relevant information
      placeholder: 'Add any other context, screenshots, or relevant information here'
      render: markdown

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Blocks development)
        - High (Major functionality broken)
        - Medium (Minor functionality broken)
        - Low (Cosmetic/Documentation issue)
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment were you running when you encountered the bug?
      placeholder: 'e.g., Unity 2022.3.14f1, Windows 11'
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How often does this bug occur?
      options:
        - Always
        - Sometimes
        - Once
        - Unknown
    validations:
      required: true
