name: Feature Request
description: Suggest an idea or enhancement
title: '[FEATURE] '
labels: ['enhancement']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Brief summary of the feature request
      placeholder: 'Brief one-line summary of the feature'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the feature you're requesting
      placeholder: 'What would you like to see added or improved?'
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: 'What pain point or limitation does this address?'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work
      placeholder: 'How should this feature work?'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: 'What other approaches have you thought about?'
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Must have)
        - High (Should have)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Designs
      description: Include any mockups, wireframes, or design documents
      placeholder: 'Add screenshots, diagrams, or design documents here'
      render: markdown
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Gameplay Mechanics
        - UI/UX
        - Performance
        - Technical
        - Content/Story
        - Audio
        - Multiplayer
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Any thoughts on implementation complexity or technical considerations
      placeholder: 'What are your thoughts on how this might be implemented?'
    validations:
      required: false

  - type: textarea
    id: competition
    attributes:
      label: Competition Analysis
      description: Have you seen similar features in other games? How could they inform our approach?
      placeholder: 'List games with similar features and what you learned from them'
    validations:
      required: false
