#!/usr/bin/env bash
# generate-xref-report.sh
# Generates cross-reference report mapping GDD sections to content files
# Part of 002-doc-migration-rationalization
#
# Output: docs/design/reference/cross-reference/gdd-to-content.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Paths
DOCS_DIR="$REPO_ROOT/docs"
CONTENT_DIR="$DOCS_DIR/design/content"
OUTPUT_DIR="$DOCS_DIR/design/reference/cross-reference"
OUTPUT_FILE="$OUTPUT_DIR/gdd-to-content.md"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

echo "=== Generating GDD Cross-Reference Report ==="
echo "Scanning content files for gdd_ref links..."
echo ""

# Temporary file for collecting data
TMP_FILE=$(mktemp)
trap "rm -f $TMP_FILE" EXIT

# Function to extract gdd_ref from frontmatter
extract_gdd_ref() {
    local file="$1"
    awk '/^---$/{flag=!flag; next} flag' "$file" | grep "^gdd_ref:" | sed 's/gdd_ref:[[:space:]]*//;s/["'\''"]//g' || true
}

# Function to extract title from frontmatter
extract_title() {
    local file="$1"
    awk '/^---$/{flag=!flag; next} flag' "$file" | grep "^title:" | sed 's/title:[[:space:]]*//;s/["'\''"]//g' || true
}

# Scan all content files
TOTAL_FILES=0
FILES_WITH_GDDREF=0

while IFS= read -r -d '' file; do
    ((TOTAL_FILES++))

    gdd_ref=$(extract_gdd_ref "$file")

    if [[ -n "$gdd_ref" ]]; then
        ((FILES_WITH_GDDREF++))

        # Get relative path from content/
        rel_path="${file#$CONTENT_DIR/}"

        # Get title
        title=$(extract_title "$file")

        # Write to temp file: gdd_ref | title | rel_path
        echo "$gdd_ref|$title|$rel_path" >> "$TMP_FILE"
    fi
done < <(find "$CONTENT_DIR" -name "*.md" -type f ! -path "*/_*" -print0)

echo "Found $FILES_WITH_GDDREF content files with gdd_ref (out of $TOTAL_FILES total)"
echo ""

# Sort by gdd_ref
sort "$TMP_FILE" -o "$TMP_FILE"

# Generate markdown report
cat > "$OUTPUT_FILE" <<EOF
# GDD to Content Cross-Reference

**Generated**: $(date -u +"%Y-%m-%d %H:%M UTC")
**Feature**: 002-doc-migration-rationalization
**Purpose**: Maps authoritative GDD sections to content files that reference them

---

## Summary

- **Total Content Files**: $TOTAL_FILES
- **Files with gdd_ref**: $FILES_WITH_GDDREF
- **Coverage**: $(awk "BEGIN {printf \"%.1f\", ($FILES_WITH_GDDREF/$TOTAL_FILES)*100}")%

---

## Cross-Reference Map

Format: Each GDD section lists all content files that reference it.

EOF

# Group by gdd_ref and generate sections
current_gdd=""
current_section=""

while IFS='|' read -r gdd_ref title rel_path; do
    # Parse gdd_ref
    gdd_path="${gdd_ref%%#*}"
    section_id="${gdd_ref##*#}"

    # If section ID is same as path (no #), use "General"
    if [[ "$gdd_path" == "$section_id" ]]; then
        section_id="(General)"
    fi

    # If new GDD file, print header
    if [[ "$gdd_path" != "$current_gdd" ]]; then
        current_gdd="$gdd_path"

        # Print GDD file header
        echo "" >> "$OUTPUT_FILE"
        echo "### $gdd_path" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi

    # If new section, print section header
    if [[ "$section_id" != "$current_section" ]]; then
        current_section="$section_id"

        # Print section header
        echo "#### #$section_id" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi

    # Print content file link
    echo "- [$title]($CONTENT_DIR/$rel_path)" >> "$OUTPUT_FILE"

done < "$TMP_FILE"

# Footer
cat >> "$OUTPUT_FILE" <<EOF

---

## Usage

This cross-reference map enables:

1. **GDD Impact Analysis**: When updating a GDD section, find all affected content
2. **Content Validation**: Verify content files correctly reference authoritative mechanics
3. **Documentation Coverage**: Identify GDD sections with few/no content examples

---

## Validation

To validate all gdd_ref links:

\`\`\`bash
.specify/scripts/validate-gdd-references.sh
\`\`\`

---

_Generated by generate-xref-report.sh from 002-doc-migration-rationalization_
EOF

echo "Cross-reference report generated at:"
echo "  $OUTPUT_FILE"
echo ""
echo "=== Report Statistics ==="
echo "Total content files: $TOTAL_FILES"
echo "Files with gdd_ref: $FILES_WITH_GDDREF"
echo "Coverage: $(awk "BEGIN {printf \"%.1f\", ($FILES_WITH_GDDREF/$TOTAL_FILES)*100}")%"
