using Reqnroll;
using RealmsOfIdle.Core.Engine.Spatial;
using RealmsOfIdle.SimulationTests.Infrastructure;
using RealmsOfIdle.SimulationTests.Infrastructure.Drivers;
using AwesomeAssertions;

namespace RealmsOfIdle.SimulationTests.Features.Inn;

[Binding]
public class InnLayoutSteps
{
    private readonly ScenarioContext _scenarioContext;

    public InnLayoutSteps(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    private GameTestContext Context => _scenarioContext.GetGameTestContext();
    private GameEngineDriver Driver => _scenarioContext.GetGameEngineDriver();

    [Given(@"I create a new game with seed (.*)")]
    public void GivenICreateANewGameWithSeed(int seed)
    {
        Driver.CreateNewPlayer(seed);
    }

    [When(@"the inn layout is generated")]
    public void WhenTheInnLayoutIsGenerated()
    {
        // Layout is already generated by CreateNewPlayer via LayoutGenerator.GenerateInnLayout
        Context.Layout.Should().NotBeNull();
    }

    [When(@"I create another game with the same seed (.*)")]
    public void WhenICreateAnotherGameWithTheSameSeed(int seed)
    {
        // Store the first layout for comparison
        Context.Snapshots["firstLayout"] = Context.Layout!;

        // Generate a second layout with the same seed
        Context.ComparisonLayout = LayoutGenerator.GenerateInnLayout(seed);
    }

    [Then(@"the inn should have a kitchen")]
    public void ThenTheInnShouldHaveAKitchen()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        // Verify kitchen tiles exist in main hall
        var hasKitchen = HasFurnitureWithId(mainHall!, "kitchen");
        hasKitchen.Should().BeTrue();
    }

    [Then(@"the inn should have a bar")]
    public void ThenTheInnShouldHaveABar()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        var hasBar = HasFurnitureWithId(mainHall!, "bar");
        hasBar.Should().BeTrue();
    }

    [Then(@"the inn should have (.*) tables")]
    public void ThenTheInnShouldHaveTables(int expectedCount)
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        var tableCount = CountFurnitureWithPrefix(mainHall!, "table_");
        tableCount.Should().Be(expectedCount);
    }

    [Then(@"the inn should have a fireplace")]
    public void ThenTheInnShouldHaveAFireplace()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        var hasFireplace = HasFurnitureWithId(mainHall!, "fireplace");
        hasFireplace.Should().BeTrue();
    }

    [Then(@"the inn should have guest rooms")]
    public void ThenTheInnShouldHaveGuestRooms()
    {
        var layout = Context.Layout!;
        var guestWing = layout.GetArea("area_guest_wing");
        guestWing.Should().NotBeNull();

        var guestBedCount = CountFurnitureWithPrefix(guestWing!, "guest_bed_");
        guestBedCount.Should().BeGreaterThan(0);
    }

    [Then(@"the inn should have an entrance")]
    public void ThenTheInnShouldHaveAnEntrance()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        // Entrance is a door tile on the north wall (y=0)
        mainHall!.DoorTiles.Should().NotBeEmpty();
    }

    [Then(@"all areas should be path-connected")]
    public void ThenAllAreasShouldBePathConnected()
    {
        var layout = Context.Layout!;
        layout.DoorConnections.Count.Should().BeGreaterThanOrEqualTo(2,
            because: "main hall should connect to staff quarters and guest wing");
    }

    [Then(@"the layout should be identical to the first layout")]
    public void ThenTheLayoutShouldBeIdenticalToTheFirstLayout()
    {
        var firstLayout = (WorldLayout)Context.Snapshots["firstLayout"];
        var secondLayout = Context.ComparisonLayout!;

        // Both layouts should have the same number of areas
        firstLayout.Areas.Count.Should().Be(secondLayout.Areas.Count);

        // Both layouts should have the same number of door connections
        firstLayout.DoorConnections.Count.Should().Be(secondLayout.DoorConnections.Count);

        // Both should have matching area IDs
        for (int i = 0; i < firstLayout.Areas.Count; i++)
        {
            firstLayout.Areas[i].Id.Should().Be(secondLayout.Areas[i].Id,
                because: "deterministic seed should produce identical area IDs");
        }
    }

    [Then(@"the kitchen should be in a corner or on the back wall")]
    public void ThenTheKitchenShouldBeInACornerOrOnTheBackWall()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        // Kitchen is placed at startX=1, near the south wall (back wall)
        // Verify kitchen furniture exists in the expected region
        var kitchenPositions = FindFurniturePositions(mainHall!, "kitchen");
        kitchenPositions.Should().NotBeEmpty();

        // Kitchen should be in the lower-left area (corner/back wall)
        foreach (var pos in kitchenPositions)
        {
            // Kitchen is placed starting at x=1 (near left wall) and y near height-4 (back wall)
            pos.X.Should().BeLessThan(mainHall!.Grid.Width / 2, because: "kitchen should be on the left side");
        }
    }

    [Then(@"the kitchen should be connected to the main hall")]
    public void ThenTheKitchenShouldBeConnectedToTheMainHall()
    {
        // Kitchen is placed directly in the main hall, so it's inherently connected
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();
        HasFurnitureWithId(mainHall!, "kitchen").Should().BeTrue();
    }

    [Then(@"tables should be placed in the open floor area")]
    public void ThenTablesShouldBePlacedInTheOpenFloorArea()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        var tablePositions = FindFurniturePositions(mainHall!, "table_");
        tablePositions.Should().NotBeEmpty();

        // Tables should not be on walls (x>0, y>0, x<width-1, y<height-1)
        foreach (var pos in tablePositions)
        {
            pos.X.Should().BeGreaterThan(0);
            pos.Y.Should().BeGreaterThan(0);
            pos.X.Should().BeLessThan(mainHall!.Grid.Width - 1);
            pos.Y.Should().BeLessThan(mainHall.Grid.Height - 1);
        }
    }

    [Then(@"no two tables should overlap")]
    public void ThenNoTwoTablesShouldOverlap()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        var tablePositions = FindFurniturePositions(mainHall!, "table_");
        var positionSet = new HashSet<(int, int)>();

        foreach (var pos in tablePositions)
        {
            var tuple = (pos.X, pos.Y);
            positionSet.Should().NotContain(tuple, because: "no two tables should overlap");
            positionSet.Add(tuple);
        }
    }

    [Then(@"the fireplace should be placed on a wall")]
    public void ThenTheFireplaceShouldBePlacedOnAWall()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        var fireplacePositions = FindFurniturePositions(mainHall!, "fireplace");
        fireplacePositions.Should().NotBeEmpty();

        // Fireplace is placed on the east wall (x = width - 1)
        foreach (var pos in fireplacePositions)
        {
            var isOnWall = pos.X == 0 || pos.X == mainHall!.Grid.Width - 1 ||
                           pos.Y == 0 || pos.Y == mainHall.Grid.Height - 1;
            isOnWall.Should().BeTrue(because: "fireplace should be on a wall");
        }
    }

    [Then(@"the fireplace should not block any doorways")]
    public void ThenTheFireplaceShouldNotBlockAnyDoorways()
    {
        var layout = Context.Layout!;
        var mainHall = layout.GetArea("area_main_hall");
        mainHall.Should().NotBeNull();

        var fireplacePositions = FindFurniturePositions(mainHall!, "fireplace");
        var doorPositions = mainHall!.DoorTiles;

        foreach (var pos in fireplacePositions)
        {
            var gridPos = new GridPosition(pos.X, pos.Y);
            doorPositions.Should().NotContain(gridPos, because: "fireplace should not block doorways");
        }
    }

    [Then(@"the inn should have staff quarters")]
    public void ThenTheInnShouldHaveStaffQuarters()
    {
        var layout = Context.Layout!;
        var staffQuarters = layout.GetArea("area_staff_quarters");
        staffQuarters.Should().NotBeNull();
    }

    [Then(@"the staff quarters should be connected to the main hall")]
    public void ThenTheStaffQuartersShouldBeConnectedToTheMainHall()
    {
        var layout = Context.Layout!;
        var hasConnection = layout.DoorConnections.Any(dc =>
            dc.ConnectsAreas("area_main_hall", "area_staff_quarters"));
        hasConnection.Should().BeTrue();
    }

    [Then(@"each staff member should have a designated bed")]
    public void ThenEachStaffMemberShouldHaveADesignatedBed()
    {
        var layout = Context.Layout!;
        var staffQuarters = layout.GetArea("area_staff_quarters");
        staffQuarters.Should().NotBeNull();

        var staffBedCount = CountFurnitureWithPrefix(staffQuarters!, "staff_bed_");
        staffBedCount.Should().BeGreaterThanOrEqualTo(3, because: "staff quarters should have beds for staff");
    }

    [Then(@"the inn should have a guest wing")]
    public void ThenTheInnShouldHaveAGuestWing()
    {
        var layout = Context.Layout!;
        var guestWing = layout.GetArea("area_guest_wing");
        guestWing.Should().NotBeNull();
    }

    [Then(@"the guest wing should be connected to the main hall")]
    public void ThenTheGuestWingShouldBeConnectedToTheMainHall()
    {
        var layout = Context.Layout!;
        var hasConnection = layout.DoorConnections.Any(dc =>
            dc.ConnectsAreas("area_main_hall", "area_guest_wing"));
        hasConnection.Should().BeTrue();
    }

    [Then(@"the guest wing should have individual rooms with beds")]
    public void ThenTheGuestWingShouldHaveIndividualRoomsWithBeds()
    {
        var layout = Context.Layout!;
        var guestWing = layout.GetArea("area_guest_wing");
        guestWing.Should().NotBeNull();

        var guestBedCount = CountFurnitureWithPrefix(guestWing!, "guest_bed_");
        guestBedCount.Should().BeGreaterThanOrEqualTo(3, because: "guest wing should have beds");
    }

    // Helper methods for tile inspection
    private static bool HasFurnitureWithId(SceneArea area, string idPrefix)
    {
        for (int x = 0; x < area.Grid.Width; x++)
        {
            for (int y = 0; y < area.Grid.Height; y++)
            {
                var facilityId = area.Grid.GetFacilityId(x, y);
                if (facilityId != null && facilityId.StartsWith(idPrefix, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
        }
        return false;
    }

    private static int CountFurnitureWithPrefix(SceneArea area, string prefix)
    {
        var uniqueIds = new HashSet<string>();
        for (int x = 0; x < area.Grid.Width; x++)
        {
            for (int y = 0; y < area.Grid.Height; y++)
            {
                var facilityId = area.Grid.GetFacilityId(x, y);
                if (facilityId != null && facilityId.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                {
                    uniqueIds.Add(facilityId);
                }
            }
        }
        return uniqueIds.Count;
    }

    private static List<(int X, int Y)> FindFurniturePositions(SceneArea area, string idPrefix)
    {
        var positions = new List<(int X, int Y)>();
        for (int x = 0; x < area.Grid.Width; x++)
        {
            for (int y = 0; y < area.Grid.Height; y++)
            {
                var facilityId = area.Grid.GetFacilityId(x, y);
                if (facilityId != null && facilityId.StartsWith(idPrefix, StringComparison.OrdinalIgnoreCase))
                {
                    positions.Add((x, y));
                }
            }
        }
        return positions;
    }
}
